# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d7b555c70d1b39f5eb271f54d3470fa400bbb19665c8355953c003238aacc0db9acd076cc6d5f3d2b979d2365daf02bfc8ad22554e7b56afa33b8cfa7abcb52

test:
  secret_key_base: 590dd5c0ba554bce0ef86a72f79d069fa7c6a13864b19c8d121e6142c0f0b29c94489f8cdc118c95624b0b7006e19e0a66a4739827df47f0142e8af6c143cc78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
